apiVersion: apps/v1
kind: Deployment
metadata:
  name: abhishek-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-fashion-site
  template:
    metadata:
      labels:
        app: my-fashion-site
    spec:
      containers:
      - name: abhishek-fashion-web
        # Using your actual ECR link with the latest tag for the CI/CD pipeline
        image: 481048082259.dkr.ecr.ap-south-1.amazonaws.com/abhishek-fashion-web:latest
        ports:
        - containerPort: 80
        # This is the "Brain" part for the Autoscaler
        resources:
          requests:
            cpu: "100m"      # Reserved CPU
            memory: "128Mi"  # Reserved RAM
          limits:
            cpu: "250m"      # Max CPU
            memory: "256Mi"  # Max RAM
---
apiVersion: v1
kind: Service
metadata:
  name: abhishek-web-service
spec:
  type: LoadBalancer
  selector:
    app: my-fashion-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80